# Generated by Django 4.2.13 on 2024-05-23 18:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='new_body',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('pic', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Select image')), ('decorative', wagtail.blocks.BooleanBlock(default=False, label='Image is decorative', required=False)), ('alt_text', wagtail.blocks.CharBlock(required=False))]))]))], blank=True),
        ),
    ]
