# Generated by Django 4.2.13 on 2024-05-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thebaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thebakerpage',
            old_name='body',
            new_name='body2',
        ),
    ]
