# Generated by Django 4.2.13 on 2024-05-14 11:07

import bakerydemo.base.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thebaker', '0002_rename_body_thebakerpage_body2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thebakerpage',
            name='body2',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('image', bakerydemo.base.blocks.ImageBlock()), ('paragraph', wagtail.blocks.RichTextBlock())]),
        ),
    ]
